version: "3.8"
services:
  # Existing Node.js application service
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=HarminderKaur12345678  # Replace with your name + student ID
      - POSTGRES_DB=labonedb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  # New PostgreSQL database service
  db:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_DB=labonedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=HarminderKaur12345678  # Replace with your name + student ID
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
